import fs from "node:fs/promises";
import path from "node:path";
import { pathExists } from "./fs.js";

export const WT_MANAGED_ENV_BLOCK_START = "# >>> WT MANAGED ENV >>>";
export const WT_MANAGED_ENV_BLOCK_END = "# <<< WT MANAGED ENV <<<";

export const WT_MANAGED_ENV_KEYS = Object.freeze([
  "WT_SUPABASE_ENV_MODE",
  "WT_SUPABASE_WORKDIR",
  "WT_SUPABASE_PROJECT_ID",
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_SECRET_KEY",
  "SUPABASE_JWT_SECRET",
  "VITE_PUBLIC_SUPABASE_URL",
  "VITE_PUBLIC_SUPABASE_ANON_KEY",
  "POSTGRES_HOST",
  "POSTGRES_USER",
  "POSTGRES_PASSWORD",
  "POSTGRES_DATABASE",
  "POSTGRES_URL",
  "POSTGRES_URL_NON_POOLING",
  "POSTGRES_PRISMA_URL",
  "LOCAL_DB_URL",
]);

export async function upsertManagedEnvFile(input: {
  envPath: string;
  values: Record<string, string>;
}): Promise<void> {
  const current = (await pathExists(input.envPath))
    ? await fs.readFile(input.envPath, "utf8")
    : "";

  const updated = upsertManagedEnvBlock(current, input.values);
  await fs.mkdir(path.dirname(input.envPath), { recursive: true });
  await fs.writeFile(input.envPath, updated);
}

export async function removeManagedEnvFileBlock(envPath: string): Promise<void> {
  if (!(await pathExists(envPath))) {
    return;
  }

  const current = await fs.readFile(envPath, "utf8");
  const withoutBlock = stripMarkerBlock(
    current,
    WT_MANAGED_ENV_BLOCK_START,
    WT_MANAGED_ENV_BLOCK_END,
  );
  const cleaned = stripManagedEnvAssignments(withoutBlock);
  await fs.writeFile(envPath, normalizeTrailingNewline(cleaned));
}

export function upsertManagedEnvBlock(content: string, values: Record<string, string>): string {
  assertMarkerPairIntegrity(content, WT_MANAGED_ENV_BLOCK_START, WT_MANAGED_ENV_BLOCK_END);
  const withoutBlock = stripMarkerBlock(
    content,
    WT_MANAGED_ENV_BLOCK_START,
    WT_MANAGED_ENV_BLOCK_END,
  );
  const withoutManagedAssignments = stripManagedEnvAssignments(withoutBlock);
  const base = withoutManagedAssignments.trimEnd();
  const block = renderManagedEnvBlock(values);

  return `${base}${base.length > 0 ? "\n\n" : ""}${block}\n`;
}

export function renderManagedEnvBlock(values: Record<string, string>): string {
  const lines = [
    WT_MANAGED_ENV_BLOCK_START,
    "# This block is auto-generated by wt.",
    "# Do not edit manually. Re-run `wt db emancipate` or `wt db rejoin`.",
  ];

  for (const key of WT_MANAGED_ENV_KEYS) {
    const value = values[key];

    if (value === undefined) {
      continue;
    }

    lines.push(`${key}=${JSON.stringify(value)}`);
  }

  lines.push(WT_MANAGED_ENV_BLOCK_END);
  return lines.join("\n");
}

export function stripManagedEnvAssignments(content: string): string {
  const managedKeys = new Set<string>(WT_MANAGED_ENV_KEYS);

  return content
    .split(/\r?\n/)
    .filter((line) => {
      const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/);
      return !match?.[1] || !managedKeys.has(match[1]);
    })
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

export function stripMarkerBlock(content: string, startMarker: string, endMarker: string): string {
  const startCount = assertMarkerPairIntegrity(content, startMarker, endMarker);

  if (startCount === 0) {
    return content;
  }

  const startIndex = content.indexOf(startMarker);
  const endIndex = content.indexOf(endMarker);
  const endMarkerEndIndex = endIndex + endMarker.length;
  return `${content.slice(0, startIndex)}${content.slice(endMarkerEndIndex)}`;
}

export function assertMarkerPairIntegrity(
  content: string,
  startMarker: string,
  endMarker: string,
): number {
  const startCount = countOccurrences(content, startMarker);
  const endCount = countOccurrences(content, endMarker);

  if (startCount !== endCount) {
    throw new Error("Managed env block markers are unbalanced.");
  }

  if (startCount > 1) {
    throw new Error("Managed env block appears multiple times.");
  }

  return startCount;
}

function countOccurrences(content: string, fragment: string): number {
  let count = 0;
  let index = 0;

  while (true) {
    const found = content.indexOf(fragment, index);

    if (found < 0) {
      return count;
    }

    count += 1;
    index = found + fragment.length;
  }
}

function normalizeTrailingNewline(content: string): string {
  const trimmed = content.trimEnd();
  return trimmed.length > 0 ? `${trimmed}\n` : "";
}
